l_english:
 belgian_nation_title: "Form Belgian Nation"
 belgian_nation_desc: "The Flemish and Wallonian people have been divided long enough. To prevent out peoples being divided amongst those who would conquer us, we must unite and become stronger than ever."
 battlefield_of_europe: "Battlefield of Europe"
 battlefield_of_europe_desc: "Belgium has often been referred to as the battlefield of europe, due to the geographic location of the nation, many armies passed through the low countries. Over the centuries the Belgians have become adept at defense."
 skirmishers: "Skirmishers"
 skirmishers_desc: "Belgium's volatile borders and colonial disputes have made its forces adept at smaller scale conflict"
 nationalistic_fervor: "Nationalistic Fervor"
 nationalistic_fervor_desc: "The Belgian people are willing to protect their newfound independence, even with their lives"
 colonial_beginnings: "Colonial Beginnings"
 colonial_beginnings_desc: "Belgium was never a major colonial empire, but that is not to say they were never colonial, 98% of Belgium's territory was colonial in nature"
 belgian_self_determination: "Belgian Self-Determination"
 belgian_self_determination_desc: "The Belgian people have always fought for independence, now that they have it, there is no more reason for revolt anymore"
 bel_free_trade: "Free Trade"
 bel_free_trade_desc: "Belgium has always been a strategic major center of trade, and as such in order to maintain good relations with their neighbours, a policy of free trade was in effect"
 federalisation: "Federalisation"
 federalisation_desc: "The Belgian Nation is made up of numerous different people all with unique cultures, the best way to maintain a stable government is to Federalise"
 BEL_ideas: "Belgian Ideas"
 BEL_ideas_start: "Belgian Ideas start"